from PyQt5 import QtCore, QtGui, QtWidgets
import datetime as dt
from booking import Booking
import firestore_service
import sys
import time

class Ui_MainWindow(object):
    def add_booking(self):
        print(self.box_name.text)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(890, 670)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(890, 670))
        MainWindow.setMaximumSize(QtCore.QSize(890, 670))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setContentsMargins(0,0,0,0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setContentsMargins(0,0,0,0)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 450, 651))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(0, 10, 461, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_2)
        self.scrollArea.setGeometry(QtCore.QRect(10, 40, 431, 601))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(450, 310, 441, 341))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.credittext = QtWidgets.QLabel(self.groupBox_3)
        self.credittext.setGeometry(QtCore.QRect(0, 300, 441, 31))
        self.credittext.setAlignment(QtCore.Qt.AlignCenter)
        self.credittext.setObjectName("credittext")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(450, 0, 441, 311))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.add_booking = QtWidgets.QLabel(self.groupBox)
        self.add_booking.setGeometry(QtCore.QRect(0, 10, 441, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.add_booking.setFont(font)
        self.add_booking.setAlignment(QtCore.Qt.AlignCenter)
        self.add_booking.setObjectName("add_booking")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 40, 441, 181))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(10, 0, 10, 0)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.box_name = QtWidgets.QPlainTextEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_name.sizePolicy().hasHeightForWidth())
        self.box_name.setSizePolicy(sizePolicy)
        self.box_name.setMaximumSize(QtCore.QSize(1000, 30))
        self.box_name.setObjectName("box_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.box_name)
        self.label_name = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_name.setObjectName("label_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_name)
        self.label_petname = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_petname.setObjectName("label_petname")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_petname)
        self.dateEdit = QtWidgets.QDateEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit.sizePolicy().hasHeightForWidth())
        self.dateEdit.setSizePolicy(sizePolicy)
        self.dateEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.label_date = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_date.setObjectName("label_date")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_date)
        self.timeEdit = QtWidgets.QTimeEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit.sizePolicy().hasHeightForWidth())
        self.timeEdit.setSizePolicy(sizePolicy)
        self.timeEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.timeEdit.setObjectName("timeEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.timeEdit)
        self.label_time = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_time.setObjectName("label_time")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_time)
        self.label_phonenumber = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_phonenumber.setObjectName("label_phonenumber")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_phonenumber)
        self.box_phonenumber = QtWidgets.QPlainTextEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_phonenumber.sizePolicy().hasHeightForWidth())
        self.box_phonenumber.setSizePolicy(sizePolicy)
        self.box_phonenumber.setMaximumSize(QtCore.QSize(1000, 30))
        self.box_phonenumber.setObjectName("box_phonenumber")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.box_phonenumber)
        self.box_petname = QtWidgets.QPlainTextEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_petname.sizePolicy().hasHeightForWidth())
        self.box_petname.setSizePolicy(sizePolicy)
        self.box_petname.setMaximumSize(QtCore.QSize(1000, 30))
        self.box_petname.setObjectName("box_petname")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.box_petname)
        self.result_text = QtWidgets.QLabel(self.groupBox)
        self.result_text.setGeometry(QtCore.QRect(0, 230, 441, 21))
        self.result_text.setText("")
        self.result_text.setAlignment(QtCore.Qt.AlignCenter)
        self.result_text.setObjectName("result_text")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 250, 441, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout.setSpacing(40)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancel_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_button.sizePolicy().hasHeightForWidth())
        self.cancel_button.setSizePolicy(sizePolicy)
        self.cancel_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.add_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_button.sizePolicy().hasHeightForWidth())
        self.add_button.setSizePolicy(sizePolicy)
        self.add_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.add_button.setObjectName("add_button")
        self.horizontalLayout.addWidget(self.add_button)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(False)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.refresh_button = QtWidgets.QPushButton(self.groupBox_2)
        self.refresh_button.setGeometry(QtCore.QRect(370, 5, 71, 31))
        self.refresh_button.setObjectName("refresh_button")

        #dynamic list 
        self.update_list()
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #function
        timenow = dt.datetime.now()
        self.dateEdit.setDate(timenow.date())
        self.dateEdit.setDisplayFormat(r'd/M/yyyy')
        self.timeEdit.setTime(timenow.replace(hour=8,minute=0).time())
        self.add_button.clicked.connect(self.clicked_add)
        self.cancel_button.clicked.connect(self.clicked_cancel)
        self.refresh_button.clicked.connect(self.update_list)

    def update_list(self):
        _translate = QtCore.QCoreApplication.translate
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setSpacing(0)
        dates = firestore_service.get_dates()
        for date in dates:
            dayname = dt.datetime(year=date.year,month=date.month,day=date.day).strftime("%A")
            datelabel = QtWidgets.QLabel()
            datelabel.setObjectName("label_date")
            datelabel.setText(_translate("MainWindow", str(date.day) +'/'+str(date.month) +'/'+str(date.year)+' '+dayname))
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(datelabel.sizePolicy().hasHeightForWidth())
            datelabel.setSizePolicy(sizePolicy)
            datelabel.setMinimumSize(QtCore.QSize(0, 20))
            datelabel.setMaximumSize(QtCore.QSize(16777215, 20))
            font = QtGui.QFont()
            font.setPointSize(10)
            datelabel.setFont(font)
            self.verticalLayout.addWidget(datelabel)
            for booking in firestore_service.booking_list:
                if(booking.datetime.date()==date):
                    horizontalbox = QtWidgets.QFrame()
                    horizontalLayoutWidget = QtWidgets.QWidget()
                    horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 240, 411, 80))
                    horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
                    horizontalLayout = QtWidgets.QHBoxLayout(horizontalLayoutWidget)
                    horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
                    horizontalLayout.setContentsMargins(0, 0, 0, 0)
                    horizontalLayout.setObjectName("horizontalLayout")
                    font = QtGui.QFont()
                    font.setPointSize(9)
                    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
                    display_text = QtWidgets.QLabel(horizontalLayoutWidget)
                    display_text.setMinimumHeight(70)
                    display_text.setFont(font)
                    display_text.setMaximumSize(QtCore.QSize(350, 70))
                    display_text.setFrameShape(QtWidgets.QFrame.Box)
                    display_text.setFrameShadow(QtWidgets.QFrame.Raised)
                    display_text.setTextFormat(QtCore.Qt.PlainText)
                    display_text.setWordWrap(True)
                    display_text.setSizePolicy(sizePolicy)
                    display_text.setObjectName("display_text")
                    horizontalLayout.addWidget(display_text)
                    pushButton = QtWidgets.QPushButton(horizontalLayoutWidget)
                    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
                    pushButton.setMinimumHeight(70)
                    pushButton.clicked.connect(lambda dummy='', id=booking.id:self.clicked_delete(dummy,id))
                    pushButton.setText(_translate("MainWindow", "Delete"))
                    pushButton.setMaximumHeight(70)
                    sizePolicy.setHorizontalStretch(0)
                    sizePolicy.setVerticalStretch(0)
                    sizePolicy.setHeightForWidth(pushButton.sizePolicy().hasHeightForWidth())
                    pushButton.setSizePolicy(sizePolicy)
                    pushButton.setObjectName("pushButton")
                    horizontalLayout.addWidget(pushButton)
                    display_text.setText(_translate("MainWindow", booking.__str__()))
                    horizontalbox.setLayout(horizontalLayout)
                    horizontalbox.setMaximumHeight(70)
                    self.verticalLayout.addWidget(horizontalbox)
                    
            self.verticalBox = QtWidgets.QFrame()
            self.verticalBox.setLayout(self.verticalLayout)
            self.scrollArea.setWidget(self.verticalBox)
            self.scrollArea.show()
    
    def clicked_add(self):
        timenow = dt.datetime.now()
        name = self.box_name.toPlainText()
        phone_number = self.box_phonenumber.toPlainText()
        petname = self.box_petname.toPlainText()
        datetime = dt.datetime(year=self.dateEdit.date().year(),month=self.dateEdit.date().month(),
        day=self.dateEdit.date().day(),hour=self.timeEdit.time().hour(),minute=self.timeEdit.time().minute())
        self.box_name.clear()
        self.box_phonenumber.clear()
        self.box_petname.clear()
        self.dateEdit.setDate(timenow.date())
        self.timeEdit.setTime(timenow.replace(hour=8,minute=0).time())
        if name != '' and phone_number != '' and petname != '' and datetime>timenow:
            new_booking = Booking()
            new_booking.name = name
            new_booking.phone_number = phone_number
            new_booking.pet_name = petname
            new_booking.time_slot = int(datetime.timestamp())
            firestore_service.add_booking(new_booking)
            self.result_text.setText('Booking added successfully.')
            time.sleep(0.5)
            self.update_list()

    def clicked_cancel(self):
        timenow = dt.datetime.now()
        self.box_name.clear()
        self.box_phonenumber.clear()
        self.box_petname.clear()
        self.dateEdit.setDate(timenow.date())
        self.timeEdit.setTime(timenow.replace(hour=8,minute=0).time())

    def clicked_delete(self,dummy,id):
        firestore_service.delete_booking_by_documentid(id)
        time.sleep(0.5)
        self.update_list()

    #set text here
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PetCare Booking"))
        MainWindow.setWindowIcon(QtGui.QIcon('icons/admin_smallicon.ico'))
        self.refresh_button.setText(_translate("MainWindow", "Refresh"))
        self.label_8.setText(_translate("MainWindow", "Booking List"))
        self.credittext.setText(_translate("MainWindow", "Created by Hafiz with <3"))
        self.add_booking.setText(_translate("MainWindow", "Add Booking"))
        self.label_name.setText(_translate("MainWindow", "Name"))
        self.label_petname.setText(_translate("MainWindow", "Pet name"))
        self.label_date.setText(_translate("MainWindow", "Date"))
        self.label_time.setText(_translate("MainWindow", "Time"))
        self.label_phonenumber.setText(_translate("MainWindow", "Phone Number"))
        self.cancel_button.setText(_translate("MainWindow", "Cancel"))
        self.add_button.setText(_translate("MainWindow", "Add"))

if __name__ == "__main__":     
    time.sleep(1)
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
